# import numpy as np

# class EVClientEnv:
#     """
#     Handles the physical modeling and MDP formulation for a single EV.
#     Based on Section 1.1 (Physical Model) and 2.3 (MDP Formulation).
#     """
#     def __init__(self, config):
#         # Vehicle Parameters [cite: 13-17]
#         self.capacity = config.get('capacity', 50.0)  # Ci in kWh
#         self.eta = config.get('efficiency', 0.95)     # eta
#         self.max_power_base = config.get('max_power', 7.0) # u_bar
#         self.dt = config.get('dt', 1.0)               # Delta t (hours)
        
#         # User Requirements [cite: 24, 25]
#         self.soc_req = config.get('soc_req', 0.9)     # Required SOC at departure
#         self.t_dep = config.get('t_dep', 10)          # Departure time step
        
#         # Grid/Penalty weights [cite: 98, 121]
#         self.alpha_satisfaction = config.get('alpha', 100.0) 
#         self.beta_grid = config.get('beta', 1.0)
        
#         # State variables
#         self.soc = config.get('initial_soc', 0.2)
#         self.current_step = 0
        
#         # External signals (Mock data for Price and Grid Signal)
#         self.forecast_horizon = config.get('H', 5)
        
#     def _get_max_power(self, soc):
#         """
#         Calculates P_max based on non-linear charging constraint.
#         Formula: P_max = u_bar * (1 - alpha * SOC) 
#         """
#         alpha_constraint = 0.1 # Example coefficient
#         return self.max_power_base * (1 - alpha_constraint * soc)

#     def get_state(self, grid_signal, voltage_dev, price_forecast):
#         """
#         Constructs the state vector s_{i,t}.
#         Definition: s_{i,t} = [SOC, t_remaining, Price_Forecast, Grid_Signal, Voltage_Dev]
#         [cite: 85, 121]
#         """
#         t_remaining = self.t_dep - self.current_step
        
#         # Flatten the forecast into the state vector
#         state = np.array([
#             self.soc,
#             t_remaining,
#             grid_signal,      # lambda_grid
#             voltage_dev       # delta_v
#         ] + list(price_forecast)) # Lambda_{t:t+H}
        
#         return state

#     def step(self, action_power, grid_signal, voltage_dev, price_current):
#         """
#         Executes one step in the environment.
#         Args:
#             action_power: P_{i,t} (Action)
#         Returns:
#             next_state, reward, done, info
#         """
#         # 1. Apply Constraints [cite: 21, 22]
#         p_max = self._get_max_power(self.soc)
#         # Clip power to feasible range [-P_max, P_max] (assuming symmetrical V2G)
#         p_act = np.clip(action_power, -p_max, p_max)
        
#         # 2. Update Battery Dynamics 
#         # SOC_{t+1} = SOC_t + (eta * P * dt) / C
#         delta_soc = (self.eta * p_act * self.dt) / self.capacity
#         prev_soc = self.soc
#         self.soc = np.clip(self.soc + delta_soc, 0.0, 1.0)
        
#         self.current_step += 1
        
#         # 3. Calculate Reward [cite: 86-91, 121]
#         # Term 1: Energy Cost
#         r_cost = -(price_current * p_act * self.dt)
        
#         # Term 2: Grid Penalty (Voltage/Congestion)
#         # Modeled as penalty on voltage deviation or grid signal
#         r_grid = -self.beta_grid * (voltage_dev**2 + grid_signal * abs(p_act))
        
#         # Term 3: Satisfaction Penalty (Only at departure)
#         r_satisfaction = 0
#         done = False
        
#         if self.current_step >= self.t_dep:
#             done = True
#             if self.soc < self.soc_req:
#                 # Penalty: alpha * (SOC_req - SOC_final)^2 [cite: 91]
#                 r_satisfaction = -self.alpha_satisfaction * ((self.soc_req - self.soc)**2)
        
#         total_reward = r_cost + r_grid + r_satisfaction
        
#         return total_reward, done, self.soc





import numpy as np
import math

# We use absolute imports to be robust across the modular structure
from utils.config_loader import get_config
from utils.reward_functions import compute_reward

# Location constants
LOC_HOME    = 0
LOC_OFFICE  = 1
LOC_DRIVING = 2

class EVClientEnv:
    """
    Handles the physical modeling and MDP formulation for a single EV.
    Configured via env.yaml and reward.yaml.

    When ``driver_behavior.enabled`` is *True* in ``env.yaml``, the
    environment additionally tracks the driver's location (home / office /
    driving) using a schedule generated by :class:`DriverBehaviorModel`.
    Charging is only possible when at home or office; driving hours
    force zero power transfer.
    """

    def __init__(self, override_env_config=None):
        """
        Args:
            override_env_config (dict): Dynamic episode-specific parameters
                                        (e.g., initial_soc, soc_req, t_dep)
                                        that override the base env.yaml constants.
        """
        # Load base configs
        self.env_config = get_config('env')
        self.reward_config = get_config('reward')

        # Merge overrides (for driver-specific parameters)
        cfg = self.env_config.copy()
        if override_env_config:
            cfg.update(override_env_config)

        # --- Physical Parameters ---
        self.capacity        = cfg.get('capacity', 60.0)
        self.eta             = cfg.get('eta', 0.95)
        self.max_power_base  = cfg.get('max_power', 11.0)
        self.dt              = cfg.get('dt', 1.0)

        # --- CC-CV Profile Coefficient ---
        self.alpha_constraint = cfg.get('alpha_constraint', 0.05)

        # --- User Requirements ---
        self.soc_req     = cfg.get('soc_req', 0.9)
        self.initial_soc = cfg.get('initial_soc', 0.2)
        self.t_dep       = cfg.get('t_dep', 12)

        # --- State Variables ---
        self.soc          = self.initial_soc
        self.current_step = 0

        # ── Driver Behavior Model ─────────────────────────────────────────
        db_cfg = self.env_config.get('driver_behavior', {})
        self.driver_behavior_enabled = db_cfg.get('enabled', False)

        # Attributes that exist regardless (safe for external inspection)
        self.driver_type      = None
        self.driver_schedule  = None
        self.current_location = LOC_HOME
        self.departure_time   = None
        self.arrival_time     = None
        self.departure_success = None
        self.episode_log      = []

        if self.driver_behavior_enabled:
            from utils.DriverBehaviorModel import DriverBehaviorModel
            seed = db_cfg.get('seed', None)
            self._behavior_model = DriverBehaviorModel(rng_seed=seed)
            self._schedule_days  = db_cfg.get('schedule_days', 5)
            self._current_day_idx = 0
            # Generate initial schedule
            self._full_schedule = self._behavior_model.generate_driver_schedule(
                days=self._schedule_days
            )
            self.driver_type = self._full_schedule['driver_type']
            self._apply_day_schedule(0)
        else:
            self._behavior_model = None

    # ── Reset ─────────────────────────────────────────────────────────────

    def reset(self, initial_soc=None, soc_req=None, t_dep=None, day_idx=None):
        """
        Resets the environment for a new episode.

        When driver behavior is enabled, samples the next day from the
        pre-generated schedule and updates location / departure / arrival.

        Args:
            initial_soc: Override initial SOC (optional).
            soc_req:     Override SOC requirement (optional).
            t_dep:       Override departure time (optional).
            day_idx:     Specific day index in the schedule (optional).
        """
        self.soc = initial_soc if initial_soc is not None else self.initial_soc
        self.current_step = 0
        self.current_location = LOC_HOME
        self.departure_success = None
        self.episode_log = []

        if soc_req is not None:
            self.soc_req = soc_req
        if t_dep is not None:
            self.t_dep = t_dep

        if self.driver_behavior_enabled:
            # Cycle through pre-generated days
            if day_idx is not None:
                idx = day_idx % self._schedule_days
            else:
                self._current_day_idx = (self._current_day_idx + 1) % self._schedule_days
                idx = self._current_day_idx
            self._apply_day_schedule(idx)

    def _apply_day_schedule(self, day_idx):
        """Loads a specific day's schedule into the environment."""
        day = self._full_schedule['days'][day_idx]
        self.driver_schedule = day
        self.departure_time  = day['home_departure']
        self.arrival_time    = day['home_arrival']
        # Override t_dep to the home departure hour for reward computation
        self.t_dep = self.departure_time

    # ── Location Logic ────────────────────────────────────────────────────

    def _update_location(self, hour):
        """
        Determine the driver's location based on the current hour and
        today's schedule.

        Transition windows (1 hour each):
            home_departure hour     → driving (home → office commute)
            office_arrival  hour    → office
            office_departure hour   → driving (office → home commute)
            home_arrival hour       → home

        All other hours fall into the region determined by the schedule
        boundaries.

        Returns:
            int: LOC_HOME (0), LOC_OFFICE (1), or LOC_DRIVING (2)
        """
        if not self.driver_behavior_enabled or self.driver_schedule is None:
            return LOC_HOME  # legacy: always at home

        h = hour % 24
        hd = self.driver_schedule['home_departure']
        oa = self.driver_schedule['office_arrival']
        od = self.driver_schedule['office_departure']
        ha = self.driver_schedule['home_arrival']

        # Morning commute: driving FROM home departure TO office arrival
        if hd <= oa:
            if hd <= h < oa:
                return LOC_DRIVING
        else:
            if h >= hd or h < oa:
                return LOC_DRIVING

        # At office: between office arrival and office departure
        if oa <= od:
            if oa <= h < od:
                return LOC_OFFICE
        else:
            if h >= oa or h < od:
                return LOC_OFFICE

        # Evening commute: driving FROM office departure TO home arrival
        if od <= ha:
            if od <= h < ha:
                return LOC_DRIVING
        else:
            if h >= od or h < ha:
                return LOC_DRIVING

        # Otherwise: at home
        return LOC_HOME

    # ── Physics ───────────────────────────────────────────────────────────

    def _get_max_power(self, soc):
        """
        Non-linear CC-CV charging constraint.
        P_max = ū · (1 − α · SOC)
        """
        return self.max_power_base * (1 - self.alpha_constraint * soc)

    # ── State ─────────────────────────────────────────────────────────────

    def get_state(self, grid_signal, voltage_dev, price_forecast,
                  ev_total_mw=0.0, delta_ev_mw=0.0):
        """
        Constructs and normalises the state vector s_{i,t}.

        Base (13-dim):
            [SOC, t_sin, t_cos, t_remaining, grid, voltage,
             ev_total, ev_delta, *prices(5)]

        Extended (16-dim, when driver_behavior enabled):
            [...base, loc_home, loc_office, loc_driving]
        """
        s_soc = self.soc

        # Cyclic time encoding
        hour_of_day = self.current_step % 24
        t_sin = math.sin(2 * math.pi * hour_of_day / 24.0)
        t_cos = math.cos(2 * math.pi * hour_of_day / 24.0)

        # Remaining time to departure, normalised
        t_remaining_norm = (self.t_dep - self.current_step) / 24.0

        # Grid & voltage — clipped and scaled
        s_grid = np.clip(grid_signal, 0.0, 1.0)
        s_volt = np.clip(voltage_dev * 10.0, -1.0, 1.0)

        # Price forecast
        s_prices = [p / 0.50 for p in price_forecast]

        # Aggregate EV load signals
        s_ev_total = np.clip(ev_total_mw / 0.25,  0.0,  1.0)
        s_ev_delta = np.clip(delta_ev_mw / 0.10, -1.0,  1.0)

        features = [
            s_soc, t_sin, t_cos, t_remaining_norm,
            s_grid, s_volt, s_ev_total, s_ev_delta,
        ] + s_prices

        # ── Location one-hot (only when driver behavior is active) ────────
        if self.driver_behavior_enabled:
            loc = self.current_location
            features += [
                1.0 if loc == LOC_HOME    else 0.0,
                1.0 if loc == LOC_OFFICE  else 0.0,
                1.0 if loc == LOC_DRIVING else 0.0,
            ]

        return np.array(features, dtype=np.float32)

    # ── Step ──────────────────────────────────────────────────────────────

    def step(self, action_power, grid_signal, voltage_dev, price_current):
        """
        Execute one MDP step.

        When driver behavior is enabled:
          • Location is updated from the schedule.
          • If driving → charging power forced to 0 (cannot charge on the road).
          • At departure time, departure_success is recorded.

        Returns:
            total_reward (float) : RL reward
            done         (bool)  : episode finished flag
            soc          (float) : updated state of charge
            energy_cost  (float) : economic cost for this step (≥ 0)
        """
        # ── 0. Location update ────────────────────────────────────────────
        if self.driver_behavior_enabled:
            self.current_location = self._update_location(self.current_step)

            # Enforce: no charging while driving
            if self.current_location == LOC_DRIVING:
                action_power = 0.0

        # ── 1. Physics & Constraints ──────────────────────────────────────
        p_max_phys = self._get_max_power(self.soc)
        p_act = np.clip(action_power, -p_max_phys, p_max_phys)
        energy_transfer = p_act * self.dt

        # Battery dynamics
        delta_soc = (self.eta * energy_transfer) / self.capacity
        prev_soc  = self.soc
        self.soc  = np.clip(self.soc + delta_soc, 0.0, 1.0)
        self.current_step += 1

        # ── 2. Economic Cost ──────────────────────────────────────────────
        energy_cost = max(0.0, energy_transfer) * price_current

        # ── 3. Structured Reward ──────────────────────────────────────────
        total_reward, done = compute_reward(
            soc=self.soc,
            prev_soc=prev_soc,
            soc_req=self.soc_req,
            t_dep=self.t_dep,
            current_step=self.current_step,
            energy_transfer=energy_transfer,
            price_current=price_current,
            grid_signal=grid_signal,
            reward_config=self.reward_config,
        )

        # ── 4. Departure constraint (driver behavior) ────────────────────
        if self.driver_behavior_enabled and done:
            self.departure_success = (self.soc >= self.soc_req)

        # ── 5. Episode log (for visualization) ────────────────────────────
        if self.driver_behavior_enabled:
            self.episode_log.append({
                'hour':           self.current_step - 1,
                'location':       self.current_location,
                'charging_power': float(p_act),
                'soc':            float(self.soc),
            })

        return total_reward, done, self.soc, energy_cost










